### ISSUE TITLE
Unable to scale the cards

### ISSUE THREAD

**Issue by shashankjamdade** [mayuroks/CardStackLayoutManager#1]
I am trying to make 'Google nebourly' sliding card animation like below but I unable to do that using this library. How to do so. plz help

**TARGET:**
![googlenebourly](https://user-images.githubusercontent.com/17645384/46459010-4686c900-c7d5-11e8-9869-7ac97239beed.png)
............................................

**ACTUAL:**
![cardstack](https://user-images.githubusercontent.com/17645384/46458845-c19baf80-c7d4-11e8-8c18-9034bc1fd98a.png)

**Comment by mayuroks** [comment]
@shashankjamdade This is my side project and I am not actively working on it. The core idea is to figure out the algorithm that handles card sliding slide in the LayoutManager. 

But I haven't figured out a good algorithm yet. Sorry, I cannot help you with this issue. But search for custom LayoutManagers on github and you will find plenty of examples. I hope this helps.
